### PR TITLE
feat(recordings): implement PATCH recordingOptions

### PR DESCRIPTION
**Pull request by andrewazores**
# Welcome to Cryostat3! 👋
## Before contributing, make sure you have:
* [x] Read the [contributing guidelines](https://github.com/cryostatio/cryostat3/blob/main/CONTRIBUTING.md)
* [x] Linked a relevant issue which this PR resolves
* [x] Linked any other relevant issues, PR's, or documentation, if any
* [x] Resolved all conflicts, if any
* [x] Rebased your branch PR on top of the latest upstream `main` branch
* [x] Attached at least one of the following labels to the PR: `[chore, ci, docs, feat, fix, test]`
* [x] [Signed all commits using a GPG signature](https://docs.github.com/en/authentication/managing-commit-signature-verification/about-commit-signature-verification#gpg-commit-signature-verification)

**To recreate commits with GPG signature** `git fetch upstream && git rebase --force --gpg-sign upstream/main`
_______________________________________________

Related to #122
See #184
See https://github.com/cryostatio/cryostat3/issues/42
Depends on #185 

## Description of the change:
Reimplements PATCH for `recordingOptions` and  re-enables the related test.

This is not actually used in the UI anywhere and is a bit of a questionable feature - this was originally implemented to allow the user to specify default recording options (maxAge, maxSize, toDisk) that would apply to every recording they would create. It's one of the very first functionalities implemented in the original cli container-jfr project and dates back to when the user would need to choose an individual target to connect to, choose whether to set these options, then invoke recording creation upon the connected target using those options. This operation doesn't properly account for the newer "connectionless" HTTP API system either, so despite the request URL containing a `connectUrl` path param, these options are actually set globally for the whole server instance on any target.

See #184 . This is a direct port of the implementation from 2.4 which has the issues outlined above. We should decide if this feature should be dropped from the API altogether, or if it makes sense to "modernize" it and find a way to make use of it in the UI.

## How to manually test:
You could use curl/HTTPie to test the endpoint manually, but I'm not sure the value.

### CODE REVIEW

**Comment by andrewazores** [comment]
Not ready yet - looks like this is pretty flakey.

**Review by aali309 — APPROVED** [review]
LGTM

**Pull request merged**
