### PR TITLE
chore(http): remove Apache HttpClient5, replace with RESTEasy client

### PR DESCRIPTION
**Pull request by andrewazores**
# Welcome to Cryostat3! 👋
## Before contributing, make sure you have:
* [x] Read the [contributing guidelines](https://github.com/cryostatio/cryostat3/blob/main/CONTRIBUTING.md)
* [x] Linked a relevant issue which this PR resolves
* [x] Linked any other relevant issues, PR's, or documentation, if any
* [x] Resolved all conflicts, if any
* [x] Rebased your branch PR on top of the latest upstream `main` branch
* [x] Attached at least one of the following labels to the PR: `[chore, ci, docs, feat, fix, test]`
* [x] [Signed all commits using a GPG signature](https://docs.github.com/en/authentication/managing-commit-signature-verification/about-commit-signature-verification#gpg-commit-signature-verification)

**To recreate commits with GPG signature** `git fetch upstream && git rebase --force --gpg-sign upstream/main`
_______________________________________________

Fixes: #382
Depends on #342
Depends on #368

## Description of the change:
- removes Apache HttpClient5 dependency
- replaces HttpClient5 utilities with utilities from other dependencies (HTTP content type and response status code constants)
- replaces HttpClient5 actual client instance for sidecar report generation with RESTEasy client, which is *The Quarkus Way* and already a dependency

## Motivation for the change:
One less dependency to manage, more idiomatic.

## How to manually test:
1. Build PR (currently also needs manual merge of #368)
2. `./smoketest.bash -OGr -s localstack`
3. In another terminal, `podman logs -f compose_reports_1`
4. Open web client UI, generate a report
5. Check reports container log, verify that it received and processed the request (and therefore that the new HTTP client was used to send it the data)

### CODE REVIEW

**Comment by mwangggg** [comment]
hmm when I run `./mvnw clean packge`, the some tests are failing and it's not consistent- mainly `itest.ReportGenerationTest`

**Comment by andrewazores** [comment]
Seems like a weird failure, but I suppose it could have to do with the `Future`/`Uni` changes in the reports service implementation? I'll start there for troubleshooting.

Otherwise it could be a red herring and actually a problem that started with https://github.com/cryostatio/cryostat3/pull/396.

**Comment by andrewazores** [comment]
Oh nice, thanks, that's very helpful. That could be a simple rebase issue actually.

**Review by mwangggg — APPROVED** [review]
looks good!

**Pull request merged**
