### PR TITLE
feat(reports): reports sidecar, configurable caching

### PR DESCRIPTION
**Pull request by andrewazores**
Replaces #65

----

Based on #62 
Depends on #62 
Depends on https://github.com/cryostatio/cryostat-core/pull/301

1. Reimplements sidecar report generation using a `cryostat-reports` instance, configurable in `smoketest.bash` with the new `-r` flag, and
2. implements two tiers of caching:
- in-memory caching using Caffeine caches for both active and archived reports. Active report cache entries expire 10 seconds after write, archived report cache entries expire 10 minutes after the last access (read or write).
- S3 caching for archived reports. These persist until the source archived recording is deleted through the Cryostat API, and also have an S3 expiration of 1 day after creation, but this requires the S3 provider to actually implement this object expiry pruning proactively which not all may do. The Cryostat server sends this expiry data metadata along with the cached report object to S3, so it's up to the provider to actually execute upon at that point.

Reports sourced from active recordings are never stored in S3-backed cache, because active recordings are assumed to be too dynamic and rapidly-changing to make sense to cache this way. They are cached in-memory only and for a short duration by default simply to reduce the cost of clients rapidly requesting report generations for the same recording.

Reports sourced from archived recordings are sourced from the in-memory cache if available. If not, they are sourced from the S3-backed cache if available. If not, then they are freshly generated, then stored in S3, then stored in memory, and returned to the client. Since archived reports are (by definition) static data, the in-memory cache duration for them is longer by default to improve performance while also (hopefully) not collecting too many and exerting undue memory pressure on the Cryostat server. If an archived recording report is requested after it has been evicted from in-memory cache then it will be retrieved from S3 rather than regenerated, since this should also be a much cheaper operation. This S3-backed scheme also means that archived reports have a lifecycle decoupled from the Cryostat server, so the Cryostat server can be restarted and the cached reports for archived recordings can still be retrieved and used to repopulate in-memory caches as needed. Here is a log snippet illustrating the tiered caching action for an archived report and a sidecar report generator:

```
s3_1                  | 2024-01-08T19:32:50.947  INFO --- [   asgi_gw_0] localstack.request.aws     : AWS s3.HeadObject => 404 (NoSuchKey)
s3_1                  | 2024-01-08T19:32:50.962  INFO --- [   asgi_gw_0] localstack.request.aws     : AWS s3.GetObject => 200
reports_1             | Jan 08, 2024 7:32:51 PM io.cryostat.reports.ReportResource handleUpload
reports_1             | INFO: Received request for null (2463387 bytes)
s3_1                  | 2024-01-08T19:32:52.252  INFO --- [   asgi_gw_0] localstack.request.http    : GET / => 200
auth_1                | [::1]:51844 - 9e48deea-4ed8-4cae-881f-bd2b8621a100 - - [2024/01/08 19:32:52] localhost:8080 GET - "/ping" HTTP/1.1 "Wget" 200 2 0.000
cryostat_1            | Jan 08, 2024 7:32:52 PM io.quarkus.vertx.http.runtime.filters.accesslog.JBossLoggingAccessLogReceiver logMessage
cryostat_1            | INFO: 10.89.1.96 - - [08/Jan/2024:19:32:52 +0000] "GET /health/liveness HTTP/1.1" 204 -
reports_1             | Jan 08, 2024 7:32:52 PM io.cryostat.reports.ReportResource cleanupHelper
reports_1             | INFO: Deleted /tmp/uploads/resteasy-reactive11145411609386885570upload
reports_1             | Jan 08, 2024 7:32:52 PM io.cryostat.reports.ReportResource cleanupHelper
reports_1             | INFO: Completed request for null after 1598ms
reports_1             | Jan 08, 2024 7:32:52 PM io.quarkus.vertx.http.runtime.filters.accesslog.JBossLoggingAccessLogReceiver logMessage
reports_1             | INFO: 10.89.1.96 - - [08/Jan/2024:19:32:52 +0000] "POST /report HTTP/1.1" 200 18254
s3_1                  | 2024-01-08T19:32:52.981  INFO --- [   asgi_gw_0] localstack.request.aws     : AWS s3.PutObject => 200
cryostat_1            | Jan 08, 2024 7:32:52 PM io.quarkus.vertx.http.runtime.filters.accesslog.JBossLoggingAccessLogReceiver logMessage
cryostat_1            | INFO: 10.89.1.99 - - [08/Jan/2024:19:32:52 +0000] "GET /api/v3/reports/YVNiM0JlSml6LVphN25xdzE1MnBmR1N1RGtMaFduWHdETXU4REoyanNqOD0vY29tcG9zZS1jcnlvc3RhdC0xX29uc3RhcnRfMjAyNDAxMDhUMTkzMjQyWi5qZnI HTTP/1.1" 200 18254
```

Here is an illustration of Cryostat retrieving a cached report from S3 after it has timed out and been evicted from the in-memory cache:

```
s3_1                  | 2024-01-08T19:53:30.346  INFO --- [   asgi_gw_0] localstack.request.aws     : AWS s3.HeadObject => 200
s3_1                  | 2024-01-08T19:53:30.350  INFO --- [   asgi_gw_0] localstack.request.aws     : AWS s3.GetObject => 200
cryostat_1            | Jan 08, 2024 7:53:30 PM io.quarkus.vertx.http.runtime.filters.accesslog.JBossLoggingAccessLogReceiver logMessage
cryostat_1            | INFO: 10.89.1.141 - - [08/Jan/2024:19:53:30 +0000] "GET /api/v3/reports/TTVTMzJobUxtVUd4Q2h5OGxvMGM2Y3dWQmhFNTVTb182bzhLMWgxVURUQT0vY29tcG9zZS1jcnlvc3RhdC0xX29uc3RhcnRfMjAyNDAxMDhUMTk1MzA2Wi5qZnI HTTP/1.1" 200 18152
auth_1                | 10.89.1.141:33564 - 725dc67d-1642-4161-8058-577d1b331f2f - user [2024/01/08 19:53:30] localhost:8080 GET cryostat "/api/v3/reports/TTVTMzJobUxtVUd4Q2h5OGxvMGM2Y3dWQmhFNTVTb182bzhLMWgxVURUQT0vY29tcG9zZS1jcnlvc3RhdC0xX29uc3RhcnRfMjAyNDAxMDhUMTk1MzA2Wi5qZnI" HTTP/1.1 "Mozilla/5.0 (X11; Linux x86_64; rv:121.0) Gecko/20100101 Firefox/121.0" 200 4690 0.016
```

The above parameters are configurable using the following new properties:

```yaml
cryostat.services.reports.url= # URL for the sidecar report generator, single instance or load balancer
quarkus.cache.enabled=true # whether in-memory Caffeine caches are globally enabled
cryostat.services.reports.memory-cache.enabled=true # whether the Caffeine caches for reports are specifically enabled
quarkus.cache.caffeine."activereports".expire-after-write=10s # how long after write to expire report caches from active recordings
quarkus.cache.caffeine."archivedreports".expire-after-access=10m # how long after access to expire report caches from archived recordings
cryostat.services.reports.storage-cache.enabled=true # whether S3-backed cache for reports are enabled
cryostat.services.reports.storage-cache.name=archivedreports # name of the S3 bucket used for archived report cache storage
cryostat.services.reports.storage-cache.expiry-duration=24h # how long after access to expire report caches from archived recordings
```

~~TODO: after rebasing, the in-memory active recording cache doesn't seem to expire on a timer, it just always returns cached entries.~~

TODO: the `MemoryCachingReportsListener` doesn't currently work as expected. When it observes Target losses, the Targets always appear to have no associated active recordings, so the listener cannot determine which entries to invalidate. This is a relatively minor issue since the cache entries will expire after a relatively short duration anyway, and each cache entry is simply the report JSON document, which is pretty small. I think this is actually a deeper issue to do with how the relation between the Target, ActiveRecording, and DiscoveryNode entities works, not specific to this PR - it's just made apparent by this cache invalidation listener.

As in previous Cryostat releases, if there is no sidecar report generator configured, then the Cryostat server itself will handle report generation requests.

### CODE REVIEW

**Comment by andrewazores** [comment]
Guess I broke something. I'll figure it out.

**Review by aali309 — DISMISSED** [review]
Looks good to me!

**Pull request merged**
