### PR TITLE
feat(grafana): implement endpoint for 'view in grafana' of archived recordings

### PR DESCRIPTION
**Pull request by andrewazores**
# Welcome to Cryostat3! 👋
## Before contributing, make sure you have:
* [x] Read the [contributing guidelines](https://github.com/cryostatio/cryostat3/blob/main/CONTRIBUTING.md)
* [x] Linked a relevant issue which this PR resolves
* [x] Linked any other relevant issues, PR's, or documentation, if any
* [x] Resolved all conflicts, if any
* [x] Rebased your branch PR on top of the latest upstream `main` branch
* [x] Attached at least one of the following labels to the PR: `[chore, ci, docs, feat, fix, test]`
* [x] [Signed all commits using a GPG signature](https://docs.github.com/en/authentication/managing-commit-signature-verification/about-commit-signature-verification#gpg-commit-signature-verification)

**To recreate commits with GPG signature** `git fetch upstream && git rebase --force --gpg-sign upstream/main`
_______________________________________________

Related to #2

## Description of the change:
Implements endpoints for "View in Grafana" feature upon archived recordings.

## Motivation for the change:
Previously, 3.0 only supported "View in Grafana" on active recordings.

## How to manually test:
1. *Run CRYOSTAT_IMAGE=quay.io... sh smoketest.sh...*
2. Find or start an active running recording
3. Archive the recording, go to Archives view
4. Find the archived recording and "View in Grafana". Verify that the Grafana dashboard appears and has sensible data content.

### CODE REVIEW

**Comment by andrewazores** [comment]
https://github.com/cryostatio/cryostat3/assets/3787464/01b6df3c-af21-4baa-88f7-c85cd5faaaf0

**Review by aali309 — APPROVED** [review]
Looks good to me.

**Pull request merged**
