### PR TITLE
test(redirects): refactor redirect handling

### PR DESCRIPTION
**Pull request by andrewazores**
# Welcome to Cryostat3! 👋
## Before contributing, make sure you have:
* [x] Read the [contributing guidelines](https://github.com/cryostatio/cryostat3/blob/main/CONTRIBUTING.md)
* [x] Linked a relevant issue which this PR resolves
* [x] Linked any other relevant issues, PR's, or documentation, if any
* [x] Resolved all conflicts, if any
* [x] Rebased your branch PR on top of the latest upstream `main` branch
* [x] Attached at least one of the following labels to the PR: `[chore, ci, docs, feat, fix, test]`
* [x] [Signed all commits using a GPG signature](https://docs.github.com/en/authentication/managing-commit-signature-verification/about-commit-signature-verification#gpg-commit-signature-verification)

**To recreate commits with GPG signature** `git fetch upstream && git rebase --force --gpg-sign upstream/main`
_______________________________________________

Related to #150

## Description of the change:
Refactors redirect handling utility methods into a WebClient extension

## Motivation for the change:
Slight clean up for encapsulation and clarify between what is a base webclient capability versus what is an extension for our integration tests only

### CODE REVIEW

**Comment by andrewazores** [comment]
@aali309 doesn't seem to have run ^ looks like everything got skipped: https://github.com/cryostatio/cryostat3/actions/runs/6813168509

**Comment by andrewazores** [comment]
https://github.com/cryostatio/cryostat3/actions/runs/6813244135

**Comment by aali309** [comment]
Works well for me after pulling latest code.
[https://github.com/aali309/cryostat3/actions/runs/6813400456](https://github.com/aali309/cryostat3/actions/runs/6813400456)
image

**Comment by andrewazores** [comment]
Not sure what you mean. This PR is already rebased on the latest `main` - is there some other code I need to pull in too?

**Comment by andrewazores** [comment]
Usually the "this job was skipped" message/status on those workflows means that there was an `if: ` condition on the workflow/step that evaluated to `false`.

https://github.com/cryostatio/cryostat3/actions/runs/6813168509/workflow

It seems like the first step must be the one that was skipped, and the rest have `needs: []` on it, so they got skipped as well since they are dependent. So really the only `if:` that causes this must be here:

https://github.com/cryostatio/cryostat3/actions/runs/6813168509/workflow#L19

I don't know why that would be evaluating to `false` though.

**Comment by aali309** [comment]
Yes, the if condition looks correct and should not be false. I was hoping it was a typo because I do that a lot. I checked the code and the updated parts looks ok. I tried removing the `owner` part on the if, it works well. But then the `build-and-test` previously also had the `if: github.repository.owner == 'cryostatio'` and it worked fine. I am still looking.

**Comment by aali309** [comment]
This does not look right. we should have two jobs here. ` build-and-test java 17` and `build-and-test java 21`
image

**Comment by andrewazores** [comment]
That could be a red herring - maybe it doesn't get fully evaluated since it's from a matrix workflow that was entirely skipped because its dependencies were skipped.

**Comment by andrewazores** [comment]
> `if: github.repository.owner == 'cryostatio'` -> `if: github.repository_owner == 'cryostatio'` This is the reason

Ah, nice find!

**Review by lkonno — APPROVED** [review]
This solution creating an extension to call the methods is much better and it will be easier to apply to the the other tests.

**Pull request merged**
