### PR TITLE
fix(graphql): avoid ConcurrentModificationException

### PR DESCRIPTION
**Pull request by andrewazores**
- fix(recording): fix NPE when starting a recording without specified template type
- fix(graphql): avoid ConcurrentModificationException

# Welcome to Cryostat3! 👋
## Before contributing, make sure you have:
* [x] Read the [contributing guidelines](https://github.com/cryostatio/cryostat3/blob/main/CONTRIBUTING.md)
* [x] Linked a relevant issue which this PR resolves
* [x] Linked any other relevant issues, PR's, or documentation, if any
* [x] Resolved all conflicts, if any
* [x] Rebased your branch PR on top of the latest upstream `main` branch
* [x] Attached at least one of the following labels to the PR: `[chore, ci, docs, feat, fix, test]`
* [x] [Signed all commits using a GPG signature](https://docs.github.com/en/authentication/managing-commit-signature-verification/about-commit-signature-verification#gpg-commit-signature-verification)

**To recreate commits with GPG signature** `git fetch upstream && git rebase --force --gpg-sign upstream/main`
_______________________________________________

Fixes: #432

## Description of the change:
*This change allows an environment variable to be configured so that...*

## Motivation for the change:
*This change is helpful because users may want to...*

## How to manually test:
1. *Run CRYOSTAT_IMAGE=quay.io... bash smoketest.bash...*
2. *...*

### CODE REVIEW

**Comment by aali309** [comment]
I will keep your changes and remove mine on [https://github.com/cryostatio/cryostat3/pull/395/commits/e9b4de4a7367dd75ca2c43338297650db3d81cf5](https://github.com/cryostatio/cryostat3/pull/395/commits/e9b4de4a7367dd75ca2c43338297650db3d81cf5)

**Review by aali309 — APPROVED** [review]
Looks good to me.

**Comment by andrewazores** [comment]
> I will keep your changes and remove mine on [e9b4de4](https://github.com/cryostatio/cryostat3/commit/e9b4de4a7367dd75ca2c43338297650db3d81cf5)

Your `transformToUni` approach is quite good too actually, that looks like it also would have worked well. It might actually be worth doing it that way too, once the current threading and transaction issues (#415 #407 etc.) are fixed up and the GraphQL nonblocking execution is re-enabled...

**Pull request merged**
