### PR TITLE
test(smoketest): update minio healthcheck to not require 'curl' in container

### PR DESCRIPTION
**Pull request by andrewazores**
# Welcome to Cryostat3! 👋
## Before contributing, make sure you have:
* [x] Read the [contributing guidelines](https://github.com/cryostatio/cryostat3/blob/main/CONTRIBUTING.md)
* [x] Linked a relevant issue which this PR resolves
* [x] Linked any other relevant issues, PR's, or documentation, if any
* [x] Resolved all conflicts, if any
* [x] Rebased your branch PR on top of the latest upstream `main` branch
* [x] Attached at least one of the following labels to the PR: `[chore, ci, docs, feat, fix, test]`
* [x] [Signed all commits using a GPG signature](https://docs.github.com/en/authentication/managing-commit-signature-verification/about-commit-signature-verification#gpg-commit-signature-verification)

**To recreate commits with GPG signature** `git fetch upstream && git rebase --force --gpg-sign upstream/main`
_______________________________________________

Fixes: #137
Based on #131
Depends on #131

### CODE REVIEW

**Comment by mwangggg** [comment]
Screenshot from 2023-11-02 14-16-44
not sure why this is happening?

**Comment by mwangggg** [comment]
`kubectl describe pod $S3_POD`

**Comment by andrewazores** [comment]
And before that, was this just a normal `smoketest.bash generate apply` off of this PR branch?

**Comment by mwangggg** [comment]
that fixed it! not sure why it wasn't working before for my setup before but it's good now

**Review by mwangggg — APPROVED** [review]

**Pull request merged**
