### PR TITLE
fix(topology): correct GraphQL schema for Topology actions, implement missing mutations

### LINKED ISSUE #302: [Task] GraphQL query for hierarchical archives

### LINKED ISSUE #304: [Task] GraphQL query for topology view display

### LINKED ISSUE #305: [Task] GraphQL mutations for topology view actions

### PR DESCRIPTION
**Pull request by andrewazores**
# Welcome to Cryostat3! 👋
## Before contributing, make sure you have:
* [x] Read the [contributing guidelines](https://github.com/cryostatio/cryostat3/blob/main/CONTRIBUTING.md)
* [x] Linked a relevant issue which this PR resolves
* [x] Linked any other relevant issues, PR's, or documentation, if any
* [x] Resolved all conflicts, if any
* [x] Rebased your branch PR on top of the latest upstream `main` branch
* [x] Attached at least one of the following labels to the PR: `[chore, ci, docs, feat, fix, test]`
* [x] [Signed all commits using a GPG signature](https://docs.github.com/en/authentication/managing-commit-signature-verification/about-commit-signature-verification#gpg-commit-signature-verification)

**To recreate commits with GPG signature** `git fetch upstream && git rebase --force --gpg-sign upstream/main`
_______________________________________________

Based on #294
Fixes #302
Fixes #304
Fixes #305

## Description of the change:
Implements missing features, fixes up a few unnecessary schema differences, and does some refactoring.

## Motivation for the change:
These changes support the existing Topology view.

## How to manually test:
1. *Run CRYOSTAT_IMAGE=quay.io... bash smoketest.bash...*
2. *...*

## Known Issues
Using the group-level Topology actions for starting a recording and then archiving that recording will frequently end up with the recording files uploaded into the wrong S3 subdirectory. The metadata labels will reflect the correct JVM ID, but the file will be listed under the wrong Target. Need to investigate why this happens.

### CODE REVIEW

**Comment by andrewazores** [comment]
The following subqueries/mutations are still missing from the schema:

```graphqls
type ArchivedRecording implements Recording {
    doDelete: ArchivedRecording!
    doPutMetadata(metadata: Object): ArchivedRecording!
}

type ActiveRecording implements Recording {
    doPutMetadata(metadata: Object): ActiveRecording
}
```

@aali309 would you like to tackle those? The archived recording deletion action already exists in `Recordings.java`, so it would be a matter of refactoring the implementation somewhere reusable (like `RecordingHelper`) and then adding the subquery to call that refactored code. In `Recordings` and `RecordingHelper` there are also already several places where recording metadata is handled, so adding some methods and subqueries to allow updating that via GraphQL should not be too complicated.

**Review by aali309 — APPROVED** [review]

**Comment by andrewazores** [comment]
@aali309 sorry for all the noise and new commits, but I did some cleaning up and I believe between this PR and https://github.com/cryostatio/cryostat-web/pull/1224 I have also solved the bug with the Archives > All Targets view.

**Comment by andrewazores** [comment]
Last couple commits fix up a behavioural conflict between #291, the GraphQL POST endpoint(s), and the discovery publication endpoint. I'm done messing with this now, anything further will come in separate follow-up PRs. @aali309 @mwangggg please re-review.

**Pull request merged**
