### PR TITLE
fix(archives): cannot delete archived recording

### PR DESCRIPTION
**Pull request by andrewazores**
# Welcome to Cryostat3! 👋
## Before contributing, make sure you have:
* [x] Read the [contributing guidelines](https://github.com/cryostatio/cryostat3/blob/main/CONTRIBUTING.md)
* [x] Linked a relevant issue which this PR resolves
* [x] Linked any other relevant issues, PR's, or documentation, if any
* [x] Resolved all conflicts, if any
* [x] Rebased your branch PR on top of the latest upstream `main` branch
* [x] Attached at least one of the following labels to the PR: `[chore, ci, docs, feat, fix, test]`
* [x] [Signed all commits using a GPG signature](https://docs.github.com/en/authentication/managing-commit-signature-verification/about-commit-signature-verification#gpg-commit-signature-verification)

**To recreate commits with GPG signature** `git fetch upstream && git rebase --force --gpg-sign upstream/main`
_______________________________________________

Fixes: #175
Related to https://github.com/cryostatio/cryostat/pull/1692 - -web is shared between the 2.4 and 3.0 server versions, and 2.4/-web expect this API change but 3.0 did not yet.

### CODE REVIEW

**Comment by andrewazores** [comment]
@mwangggg since this relates to your work around `jvmId`s vs encoded subdirectory names on the 2.4 side, would you mind taking a look around here as well to make sure the 3.0 server matches API for those endpoints?

**Comment by mwangggg** [comment]
https://github.com/cryostatio/cryostat3/blob/de4db51c85684d81d1fa3562264914ee035da393/src/main/java/io/cryostat/recordings/RecordingHelper.java#L506 I think this function can be removed now

**Comment by mwangggg** [comment]
https://github.com/cryostatio/cryostat3/actions/runs/6950023748/job/18909383953#step:13:2896 there are some errors in the tests, but we're being told the tests all pass?

**Comment by andrewazores** [comment]
#179 ^ ignore JDK 21, it ignores the test failures on purpose for now because they will not work until we upgrade to a much newer Quarkus version.

**Pull request merged**
