### PR TITLE
fix(recordings): correctly retrieve custom event templates from S3 storage

### PR DESCRIPTION
**Pull request by andrewazores**
# Welcome to Cryostat3! 👋
## Before contributing, make sure you have:
* [x] Read the [contributing guidelines](https://github.com/cryostatio/cryostat3/blob/main/CONTRIBUTING.md)
* [x] Linked a relevant issue which this PR resolves
* [x] Linked any other relevant issues, PR's, or documentation, if any
* [x] Resolved all conflicts, if any
* [x] Rebased your branch PR on top of the latest upstream `main` branch
* [x] Attached at least one of the following labels to the PR: `[chore, ci, docs, feat, fix, test]`
* [x] [Signed all commits using a GPG signature](https://docs.github.com/en/authentication/managing-commit-signature-verification/about-commit-signature-verification#gpg-commit-signature-verification)

**To recreate commits with GPG signature** `git fetch upstream && git rebase --force --gpg-sign upstream/main`
_______________________________________________

Fixes: #491
Depends on https://github.com/cryostatio/cryostat-core/pull/403
See #342
See https://github.com/cryostatio/cryostat-core/pull/389

## Description of the change:
Some recent patches to Cryostat and cryostat-core changed how event templates are handled. The current Cryostat `main` has a bug where custom event templates can be successfully uploaded to storage, listed, and downloaded back from storage, but when trying to use the template to create a new recording then the action fails. The root of the failure is that Cryostat tries to start the recording by asking the -core service implementation to start the recording using the custom event template, but that is no longer implemented in 3.0 - this is the code path that in <=2.4 would check for the custom event template on direct disk storage. The new implementation in this PR checks if the desired template is a custom one, and if so retrieves it from S3 storage first before passing it back through the same old code path to start the recording.

## How to manually test:
1. Check out related core PR, `./mvnw clean install` it. Then check out and build this PR: `./mvnw -o clean package ; podman image prune -f`. `./smoktest.bash -Ot`
2. Get a custom event template, ex. download an existing template and modify the top `<configuration>` element
3. Upload the new custom event template
4. Try to start a recording using this template

### CODE REVIEW

**Comment by andrewazores** [comment]
Ah right, CI won't work until after https://github.com/cryostatio/cryostat-core/pull/403 .

**Review by aali309 — APPROVED** [review]
Looks good to me.

**Pull request merged**
